name: Test GitHub Actions AWS Role

on:
    workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        -   name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v4
            with:
                role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                aws-region: ${{ secrets.AWS_REGION }}

        -   name: Install AWS CLI
            uses: unfor19/install-aws-cli-action@v1

        -   name: Verify identity
            run: aws sts get-caller-identity
